os: linux
sudo: required
language: minimal
services:
  - docker

before_script:
  - chmod 755 *.sh
  - docker build . --tag nn

jobs:
  include:
     - name: "tests"
       script:
         - docker run --rm -t -v $PWD:/opt/nn nn ./tests.sh
     - name: "run"
       script:
         - docker run --rm -t -v $PWD:/opt/nn nn ./run.sh
